version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nexora_postgres
    environment:
      POSTGRES_USER: nexora
      POSTGRES_PASSWORD: nexora_pass
      POSTGRES_DB: nexora_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nexora']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nexora_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nexora_api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./storage:/app/storage
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
